//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wikiPr.Ressource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wikiPr.Ressource.ResourceView", typeof(ResourceView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu.
        /// </summary>
        public static string Contenu {
            get {
                return ResourceManager.GetString("Contenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse courriel.
        /// </summary>
        public static string Courriel {
            get {
                return ResourceManager.GetString("Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière date de modification.
        /// </summary>
        public static string DateModification {
            get {
                return ResourceManager.GetString("DateModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id du contributeur.
        /// </summary>
        public static string IdContributeur {
            get {
                return ResourceManager.GetString("IdContributeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string Langue {
            get {
                return ResourceManager.GetString("Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string MDP {
            get {
                return ResourceManager.GetString("MDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de famille.
        /// </summary>
        public static string NomFamille {
            get {
                return ResourceManager.GetString("NomFamille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenom.
        /// </summary>
        public static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
    }
}
